# Generated by Django 4.2.7 on 2023-11-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location'),
        ),
    ]
